apiVersion: v1
kind: Service
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "tenant_proxy.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8031
      targetPort: 8031
      protocol: TCP
      name: http
  selector:
    app:  {{ include "acapy.fullname" . }}