apiVersion: v1
kind: Service
metadata:
  labels:
    app: apim-proxy-service
  name: apim-proxy-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pidi-tenant-proxy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
status:
  loadBalancer: {}
