apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-secret-provider
  namespace: dev
spec:
  provider: azure
  secretObjects:
  - secretName: acapy-proxy-secrets
    type: Opaque
    data:
    - objectName: ACAPY-ADMIN-URL-API-KEY
      key: adminurlkey
  - secretName: acapy-secrets
    type: Opaque
    data:
    - objectName: POSTGRES-PASSWORD
      key: postgresql-password
    - objectName: WALLET-SEED
      key: wallet-seed
    - objectName: JWT-SECRET
      key: jwt
    - objectName: WEBHOOK-API-KEY
      key: webhookapi
    - objectName: ADMIN-API-KEY
      key: admin-api-key
    - objectName: INNKEEPER-WALLET-TENANT-ID
      key: innkeeper-tenant-id
    - objectName: INNKEEPER-WALLET-WALLET-KEY
      key: innkeeper-wallet-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8ef6a9b4-3cc4-404f-b6b8-70444a6d2e4b"
    resourceGroup: "general-rg"
    keyvaultName: "pidev-general-key-vault"
    tenantID: "1aac6538-a39d-46b5-b4c7-bac599c9409f"
    objects: |
      array:
        - |
          objectName: ACAPY-ADMIN-URL-API-KEY
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
        - |
          objectName: WALLET-SEED
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: WEBHOOK-API-KEY
          objectType: secret
        - |
          objectName: ADMIN-API-KEY
          objectType: secret
        - |
          objectName: INNKEEPER-WALLET-TENANT-ID
          objectType: secret
        - |
          objectName: INNKEEPER-WALLET-WALLET-KEY
          objectType: secret
