apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant_proxy.fullname" . }}
  labels:
    {{- include "tenant_proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tenant_proxy.replicas }}
  selector:
    matchLabels:
      {{- include "tenant_proxy.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "tenant_proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: tenant-proxy
          image: "{{ .Values.tenant_proxy.image.tag }}"
          imagePullPolicy: {{ .Values.tenant_proxy.image.pullPolicy }}
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10  
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30   
          env:
            - name: ACAPY_ADMIN_URL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: acapy-secrets
                  key: admin-api-key
            - name: ACAPY_ADMIN_URL
              value: {{ include "acapy.internal.admin.url" . }}
            {{- include "tenant_proxy.configmap.env.vars" . | nindent 10}}
      volumes:
          - name: secrets-store01-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "akv-secret-provider"
