version: "3.9"
services:
  ngrok-traction-agent:
    image: wernight/ngrok
    environment:
      - ACAPY_HTTP_PORT=${ACAPY_HTTP_PORT}
    ports:
      - 4052:4040
    command: ngrok http traction-agent:${ACAPY_HTTP_PORT} --log stdout

  traction-acapy:
    build:
      context: ../plugins
      dockerfile: ./docker/Dockerfile
    image: traction-pidevgeneralcontainerregistry.azurecr.io/traction_plugins:latest

  traction-agent:
    build:
      context: ../services/aca-py
      dockerfile: Dockerfile.acapy
    depends_on:
      traction-db:
        condition: service_healthy
    environment:
      - TRACTION_ENV=${TRACTION_ENV}
      - NGROK_NAME=ngrok-traction-agent
      - ACAPY_HTTP_PORT=${ACAPY_HTTP_PORT}
      - ACAPY_GENESIS_URL=${ACAPY_GENESIS_URL}
      - ACAPY_LEDGER_BROWSER_URL=${ACAPY_LEDGER_BROWSER_URL}
      - ACAPY_ENDPOINT=${ACAPY_ENDPOINT}
      - ACAPY_WALLET_DATABASE=${ACAPY_WALLET_DATABASE}
      - ACAPY_WALLET_TYPE=${ACAPY_WALLET_TYPE}
      - ACAPY_WALLET_ENCRYPTION_KEY=${ACAPY_WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_STORAGE_TYPE=${ACAPY_WALLET_STORAGE_TYPE}
      - ACAPY_WALLET_SCHEME=${ACAPY_WALLET_SCHEME}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - ACAPY_ADMIN_PORT=${ACAPY_ADMIN_PORT}
      - AGENT_NAME=${AGENT_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ACAPY_ADMIN_CONFIG=${ACAPY_ADMIN_CONFIG}
      - ACAPY_READ_ONLY_MODE=${ACAPY_READ_ONLY_MODE}
      - ACAPY_TAILS_BASE_URL=${ACAPY_TAILS_BASE_URL}
      - ACAPY_TAILS_UPLOAD_URL=${ACAPY_TAILS_UPLOAD_URL}
      - ACAPY_ENDORSER_PUBLIC_DID=${ACAPY_ENDORSER_PUBLIC_DID}
      - ENDORSER_CONNECTION_ALIAS=${ENDORSER_CONNECTION_ALIAS}
      - TRACTION_INNKEEPER_TENANT_ID=${TRACTION_INNKEEPER_TENANT_ID}
      - TRACTION_INNKEEPER_WALLET_NAME=${TRACTION_INNKEEPER_WALLET_NAME}
      - TRACTION_INNKEEPER_WALLET_KEY=${TRACTION_INNKEEPER_WALLET_KEY}
      - TRACTION_INNKEEPER_PRINT_KEY=${TRACTION_INNKEEPER_PRINT_KEY}
      - TRACTION_INNKEEPER_PRINT_TOKEN=${TRACTION_INNKEEPER_PRINT_TOKEN}
      - TRACTION_INNKEEPER_RESERVATION_EXPIRY_MINUTES=${TRACTION_INNKEEPER_RESERVATION_EXPIRY_MINUTES}
      - TRACTION_MULTITENANT_MANAGER_CLASS=${TRACTION_MULTITENANT_MANAGER_CLASS}
      - TRACTION_MULTITENANT_ALWAYS_CHECK_PROVIDED_WALLET_KEY=${TRACTION_MULTITENANT_ALWAYS_CHECK_PROVIDED_WALLET_KEY}
      - TRACTION_MULTITENANT_ERRORS_UNNNEEDED_KEY=${TRACTION_MULTITENANT_ERRORS_UNNNEEDED_KEY}
      - TRACTION_MULTITENANT_TOKENEXPIRY_UNITS=${TRACTION_MULTITENANT_TOKENEXPIRY_UNITS}
      - TRACTION_MULTITENANT_TOKENEXPIRY_AMOUNT=${TRACTION_MULTITENANT_TOKENEXPIRY_AMOUNT}
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    entrypoint: /bin/bash
    command: ["-c", "sleep 5; ./ngrok-wait.sh"]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
    extra_hosts:
      - host.docker.internal:host-gateway

  traction-db:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tenant-ui:
    build:
      context: ../services/tenant-ui
      dockerfile: Dockerfile
    depends_on:
      tenant-proxy:
        condition: service_started
    environment:
      - SERVER_TRACTION_URL=${SERVER_TRACTION_URL}
      - FRONTEND_TENANT_PROXY_URL=${FRONTEND_TENANT_PROXY_URL}
      - IMAGE_BUILDTIME=${IMAGE_BUILDTIME}
      - IMAGE_TAG=${IMAGE_TAG}
      - IMAGE_VERSION=${IMAGE_VERSION}
      - UX_APP_TITLE=${UX_APP_TITLE}
      - UX_APP_INNKEEPER_TITLE=${UX_APP_INNKEEPER_TITLE}
      - UX_SIDEBAR_TITLE=${UX_SIDEBAR_TITLE}
      - UX_COPYRIGHT=${UX_COPYRIGHT}
      - UX_OWNER=${UX_OWNER}
      - FRONTEND_ARIES_LEDGER_DESCRIPTION=${FRONTEND_ARIES_LEDGER_DESCRIPTION}
    ports:
      - ${TENANT_UI_PORT}:8080

  tenant-proxy:
    build:
      context: ../plugins
      dockerfile: ./docker/Dockerfile.tenant-proxy
    image: pidevgeneralcontainerregistry.azurecr.io/traction-tenant-proxy:latest
    depends_on:
      traction-agent:
        condition: service_started
    restart: unless-stopped
    environment:
      - ACAPY_ADMIN_URL=${ACAPY_ADMIN_URL}
      - ACAPY_ADMIN_URL_API_KEY=${ACAPY_ADMIN_URL_API_KEY}
    ports:
      - ${TENANT_PROXY_PORT}:8080
    extra_hosts:
      - host.docker.internal:host-gateway

  endorser-api:
    build:
      context: ../services/endorser
      dockerfile: Dockerfile
    depends_on:
      endorser-agent:
        condition: service_started
      endorser-db:
        condition: service_healthy
    environment:
      - POSTGRESQL_HOST=${ENDORSER_POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${ENDORSER_PSQL_DB}
      - ENDORSER_API_ADMIN_USER=${ENDORSER_API_ADMIN_USER}
      - ENDORSER_API_ADMIN_KEY=${ENDORSER_API_ADMIN_KEY}
      - ACAPY_ADMIN_URL=${ENDORSER_ACAPY_ADMIN_URL}
      - ACAPY_ADMIN_URL_API_KEY=${ENDORSER_ACAPY_ADMIN_URL_API_KEY}
      - ENVIRONMENT=production
      - TRACTION_WEBHOOK_URL=${ENDORSER_WEBHOOK_URL}
      - ACAPY_WEBHOOK_URL_API_KEY=${ENDORSER_ACAPY_WEBHOOK_URL_API_KEY}
    ports:
      - ${ENDORSER_SERVICE_PORT}:5000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../services/endorser:/app:rw

  endorser-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc1
    depends_on:
      endorser-db:
        condition: service_healthy
    ports:
      - ${ACAPY_ENDORSER_ADMIN_PORT}:${ACAPY_ENDORSER_ADMIN_PORT}
      - ${ACAPY_ENDORSER_HTTP_PORT}:${ACAPY_ENDORSER_HTTP_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5;
        aca-py start \
        --auto-provision
        --arg-file endorser-acapy-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_ENDORSER_HTTP_PORT} \
        --webhook-url '${ENDORSER_WEBHOOK_URL}' \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY_ENDORSER_ENDPOINT} \
        --wallet-name '${ENDORSER_ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ENDORSER_ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-type '${ENDORSER_ACAPY_WALLET_TYPE}' \
        --wallet-storage-type '${ENDORSER_ACAPY_WALLET_STORAGE_TYPE}' \
        --wallet-storage-config '{\"url\":\"${ENDORSER_POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --wallet-name endorser-wallet  \
        --seed '${ACAPY_ENDORSER_SEED}' \
        --admin '0.0.0.0' ${ACAPY_ENDORSER_ADMIN_PORT} \
        --label '${ENDORSER_AGENT_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        --endorser-protocol-role endorser \
        --auto-endorse-transactions \
        ",
      ]
    volumes:
      - "./endorser-acapy-args.yml:/home/indy/endorser-acapy-args.yml"
    extra_hosts:
      - host.docker.internal:host-gateway

  endorser-db:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${ENDORSER_POSTGRESQL_PORT}:5432
    volumes:
      - endorser-wallet:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  traction-wallet:
  endorser-wallet: