version: "3.9"
services:
  ngrok-traction-agent:
    image: wernight/ngrok
    environment:
      - ACAPY_HTTP_PORT=${ACAPY_HTTP_PORT}
    ports:
      - 4052:4040
    command: ngrok http traction-agent:${ACAPY_HTTP_PORT} --log stdout

  traction-acapy:
    build:
      context: ../plugins
      dockerfile: ./docker/Dockerfile
    image: traction-local:acapy

  traction-agent:
    build:
      context: ../services/aca-py
      dockerfile: Dockerfile.acapy
    depends_on:
      traction-db:
        condition: service_healthy
    environment:
      - TRACTION_ENV=${TRACTION_ENV}
      - NGROK_NAME=ngrok-traction-agent
      - ACAPY_HTTP_PORT=${ACAPY_HTTP_PORT}
      - ACAPY_GENESIS_URL=${ACAPY_GENESIS_URL}
      - ACAPY_ENDPOINT=${ACAPY_ENDPOINT}
      - ACAPY_WALLET_DATABASE=${ACAPY_WALLET_DATABASE}
      - ACAPY_WALLET_TYPE=${ACAPY_WALLET_TYPE}
      - ACAPY_WALLET_ENCRYPTION_KEY=${ACAPY_WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_STORAGE_TYPE=${ACAPY_WALLET_STORAGE_TYPE}
      - ACAPY_WALLET_SCHEME=${ACAPY_WALLET_SCHEME}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - ACAPY_ADMIN_PORT=${ACAPY_ADMIN_PORT}
      - AGENT_NAME=${AGENT_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ACAPY_ADMIN_CONFIG=${ACAPY_ADMIN_CONFIG}
      - ACAPY_READ_ONLY_MODE=${ACAPY_READ_ONLY_MODE}
      - ACAPY_TAILS_BASE_URL=${ACAPY_TAILS_BASE_URL}
      - ACAPY_TAILS_UPLOAD_URL=${ACAPY_TAILS_UPLOAD_URL}
      - TRACTION_INNKEEPER_TENANT_ID=${TRACTION_INNKEEPER_TENANT_ID}
      - TRACTION_INNKEEPER_WALLET_NAME=${TRACTION_INNKEEPER_WALLET_NAME}
      - TRACTION_INNKEEPER_WALLET_KEY=${TRACTION_INNKEEPER_WALLET_KEY}
      - TRACTION_INNKEEPER_PRINT_KEY=${TRACTION_INNKEEPER_PRINT_KEY}
      - TRACTION_INNKEEPER_PRINT_TOKEN=${TRACTION_INNKEEPER_PRINT_TOKEN}
      - TRACTION_INNKEEPER_RESERVATION_EXPIRY_MINUTES=${TRACTION_INNKEEPER_RESERVATION_EXPIRY_MINUTES}
      - TRACTION_MULTITENANT_MANAGER_CLASS=${TRACTION_MULTITENANT_MANAGER_CLASS}
      - TRACTION_MULTITENANT_ALWAYS_CHECK_PROVIDED_WALLET_KEY=${TRACTION_MULTITENANT_ALWAYS_CHECK_PROVIDED_WALLET_KEY}
      - TRACTION_MULTITENANT_ERRORS_UNNNEEDED_KEY=${TRACTION_MULTITENANT_ERRORS_UNNNEEDED_KEY}
      - TRACTION_MULTITENANT_TOKENEXPIRY_UNITS=${TRACTION_MULTITENANT_TOKENEXPIRY_UNITS}
      - TRACTION_MULTITENANT_TOKENEXPIRY_AMOUNT=${TRACTION_MULTITENANT_TOKENEXPIRY_AMOUNT}
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    entrypoint: /bin/bash
    command: ["-c", "sleep 5; ./ngrok-wait.sh"]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"

  traction-db:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tenant-ui:
    build:
      context: ../services/tenant-ui
      dockerfile: Dockerfile
    depends_on:
      tenant-proxy:
        condition: service_started
    environment:
      - SERVER_TRACTION_URL=${SERVER_TRACTION_URL}
      - FRONTEND_TENANT_PROXY_URL=${FRONTEND_TENANT_PROXY_URL}
      - IMAGE_BUILDTIME=${IMAGE_BUILDTIME}
      - IMAGE_TAG=${IMAGE_TAG}
      - IMAGE_VERSION=${IMAGE_VERSION}
      - UX_APP_TITLE=${UX_APP_TITLE}
      - UX_APP_INNKEEPER_TITLE=${UX_APP_INNKEEPER_TITLE}
      - UX_SIDEBAR_TITLE=${UX_SIDEBAR_TITLE}
      - UX_COPYRIGHT=${UX_COPYRIGHT}
      - UX_OWNER=${UX_OWNER}
    ports:
      - ${TENANT_UI_PORT}:8080

  tenant-proxy:
    build:
      context: ../plugins
      dockerfile: ./docker/Dockerfile.tenant-proxy
    image: traction-local:tenant-proxy
    depends_on:
      traction-agent:
        condition: service_started
    restart: unless-stopped
    environment:
      - ACAPY_ADMIN_URL=${ACAPY_ADMIN_URL}
      - ACAPY_ADMIN_URL_API_KEY=${ACAPY_ADMIN_URL_API_KEY}
    ports:
      - ${TENANT_PROXY_PORT}:8080

networks:
  default:
    external: 
      name: oidc_vc_auth

volumes:
  traction-wallet:
